### ISSUE TITLE
Replace 'loading' code

### ISSUE THREAD

**Issue by jasondcater** [mountetna/timur#195]
Remove the 'exchanges'.
Remove the 'star' loader.
Add a more traditional spin loader.
Add stack logic to activate the spin loader.
-When a load cycle begins add to the stack.
-When a load cycle completes remove from the stack.
-If the stack is empty disable the spinner/loader graphic.
-If the stack is not empty activate the spinner/loader graphic.

**Comment by graft** [comment]
The 'exchanges' are exactly the sort of stack logic described. They are created and removed with API requests, and the loader spins depending on whether there are exchanges in the store.I don't see any particular reason to rebuild this, beyond perhaps a refactor/renaming.

The significant deficiency in them is that at the moment they return when fetch() returns a Promise, which indicates the start of a download, and it requires .then(response => response.json()) to actually effect a download (meaning the loader stops before the download completes). This could be fixed by moving the json() part above the exchange removal.

**Comment by jasondcater** [comment]
Per the design conversation:
Reconfigure the Exchanges to use query hashes (possible caching feature), integrate into the request cycle so the developer does not have to add/edit.
