### ISSUE TITLE
Bulk upload .czi H&E files to Timur

### ISSUE THREAD

**Issue by jvincentchan** [mountetna/timur#41]

**Comment by graft** [comment]
In order to do this I have to download the data from Box, copy it to the production machine on Amazon EC2 and from there have it post to Amazon S3 via Timur (probably in a rake task). This seems to be a pain in the ass because:

1) I cannot download files en masse from Box, it complains about file size limits.

2) Box downloads at 200kb/sec, which means if I were able to download serially it would take 70 hours. Since I have to queue each download manually, it will take a lot more.

It would be nice if there were some non-box way to receive these files.

**Comment by jvincentchan** [comment]
This is how BIOS sends it to us so even if I were to give you a HD, it would require me to download at said speed. For 1, you should be able to download it one Box folder at a time (i.e. Box 1, Box 2, Box 3, etc.). That seems to work for me and hasn't exceeded size limit. Give it a shot, I think that's the only way at this point.

________________________________

**Comment by graft** [comment]
In progress, files are on metis and need to round-trip through magma on the way to S3.

**Comment by jvincentchan** [comment]
Ok. Not sure what that means
