### ISSUE TITLE
Cannot generate/download TSV from populations table

### ISSUE THREAD

**Issue by meghanz** [mountetna/timur#52]
Getting the following error when trying to download the latest version of populations table from TIMUR:

'Your attempt to create a .tsv failed, Error: Internal Service Error'

**Comment by graft** [comment]
I was looking at this all day - this is basically a result of the same issue causing the population table (etc.) to load slowly on the flow cytometry tab - viz., retrieving a large number of records is slow. It seems this is because turning SQL rows into ruby objects is slow. This needs to be faster, but also the request should not time out.

If this is bad (for 220,000 population records), it will be worse for gene expression (4M records per plate).

**Comment by graft** [comment]
Ok, this takes 75 seconds but is possible. We'll have to improve this soon in order to make gene expression downloads viable, or maybe use background worker threads.
