### ISSUE TITLE
Valid_tree 'fails' even if sample gates match reference gates

### ISSUE THREAD

**Issue by jvincentchan** [mountetna/timur#59]
In completion metrics, if you click on a valid_tree, even if the sample is "green", Timur will say that the sample has failed even though no gates are specified.

**Comment by graft** [comment]
This appears to be a result of an empty array being converted to a vector type when you read the metrics from the manifest - not sure why this didn't crop up earlier since this I started using the manifest for metrics some time ago - I guess this would only happen for green buttons, so maybe it went unnoticed til now. Fix in progress...

**Comment by graft** [comment]
This should be fixed.
